version: '3.8'

services:
  mops:
    image: postgres:latest
    container_name: mops-db
    environment:
      POSTGRES_USER: mops
      POSTGRES_PASSWORD: mops
      POSTGRES_DB: mops
    ports:
      - "5432:5432"